USE REVISAO
--DROP TABLE VEICULO
CREATE TABLE VEICULO(
ID INT NOT NULL IDENTITY CONSTRAINT PK_VEICULO PRIMARY KEY,
NOME VARCHAR(50) NOT NULL CONSTRAINT CK_VEICULO_NOME CHECK (NOME = UPPER(NOME)),
PLACA CHAR(7) NOT NULL CONSTRAINT UK_VEICULO_PLACA UNIQUE
              CONSTRAINT CK_VEICULO_PLACA CHECK(PLACA LIKE
			  '[A-Z][A-Z][A-Z][0-9][A-Z][0-9][0-9]'),
DESCRICAO VARCHAR(200) NOT NULL,
PRECO NUMERIC(12,2) NOT NULL CONSTRAINT DF_VEICULO_PRECO DEFAULT 0
                    CONSTRAINT CK_VEICULO_PRECO CHECK (PRECO>=0),
DATAINCLUSAO DATE CONSTRAINT DF_VEICULO_DATAINCLUSAO DEFAULT GETDATE()
);
INSERT INTO VEICULO (PLACA, NOME, DESCRICAO) VALUES ('ABC1D23','BMW','BMW M3 GTR');
SELECT * FROM VEICULO

--SP_HELP VEICULO