CREATE DATABASE REVISAO
USE REVISAO
--DROP TABLE CLIENTE
CREATE TABLE CLIENTE(
ID INT NOT NULL IDENTITY CONSTRAINT PK_CLIENTE PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
CPF CHAR(14) NOT NULL CONSTRAINT UK_CLIENTE_CPF UNIQUE,
CONSTRAINT CK_CLIENTE_CPF CHECK(CPF LIKE 
'[0-9][0-9][0-9][.][0-9][0-9][0-9][.][0-9][0-9][0-9][-][0-9][0-9]'),
TIPO CHAR(1) NOT NULL CONSTRAINT CK_CLIENTE_TIPO CHECK(TIPO IN ('F','J'))
					  CONSTRAINT DF_CLIENTE_TIPO DEFAULT 'F',
LIMITECREDITO NUMERIC(10,2) NULL CONSTRAINT DF_CLIENTE_LIMITECREDITO DEFAULT 0
              CONSTRAINT CK_CLIENTE_LIMITECREDITO CHECK(LIMITECREDITO >= 0)
);
INSERT INTO CLIENTE (NOME, CPF)
VALUES ('ALBERT EINSTEIN','123.456.789-06')

SELECT * FROM CLIENTE